export const data = [
  {
    id: "16",
    title:"Best Bollywood Dumb Charades Movies Really Really Hard To Guess",
    url: "https://www.scrolldroll.com/wp-content/uploads/2018/05/Movie-name-1.jpg",
    content:"Whoever came up with this name is a genius. And before you dismiss this one, do note that besides being a great Dumb Charade movie name,  this was the first Indian film for which all songs were recorded in stereophonic sound.",
    category:"Bollywood",
    date:"On April 21, 2018.",
    width: 1280,
    height: 956,
  },
  {
    id: "17",
    title:"EVERY TIME SONGS MAKE YOU TRAVEL BACK IN TIME",
    url: "https://icdn.isrgrajan.com/in/2020/09/13-recreated-Bollywood-songs-of-2020-1-696x399.jpg",
    content:"Songs and Music are the part of the life which one cannot separate their self from. People throughout history have used songs in order to relieve their past memories and allow them to express their emotions. ",
    category:"Bollywood songs",
    date:"On December 21,2021",
    width: 500,
    height: 500,
  },
  {
    id: "18",
    title:"Indian Music and Dance Show",
    content:"The Indian Bollywood Film Star Song and Dance Troupe perform on stage during Indian Music and Dance Show at Beijing Exhibition Theater on January 31, 2010 in Beijing, China. The Indian Bollywood Film Star Song and Dance Troupe stage Indian pop songs and dance scenes from classic Bollywood films, including Rhythm of Love, Jaane Kisne, and Overjoyed Rhythm.",
    category:"Dance",
    date:"On January 31, 2010",
    url: "https://thumbs.dreamstime.com/b/indian-music-dance-show-12799791.jpg",
    width: 640,
    height: 428,
  },
  {
    id: "19",
    title:"Besharam Rang, protests",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Shah_Rukh_Khan%2C_Deepika_Padukone%2C_John_Abraham_attend_the_press_conference_and_success_celebration_of_Pathaan.jpg/200px-Shah_Rukh_Khan%2C_Deepika_Padukone%2C_John_Abraham_attend_the_press_conference_and_success_celebration_of_Pathaan.jpg",
    content:"Taran Adarsh of Bollywood Hungama rated the film 4.5 out of 5 stars and termed the film a complete entertainer replete with action, emotions, patriotism, humour, thrill, and of course, the star power of Shah Rukh Khan.[73] Sukanya Verma of Rediff gave the film a rating of 4 out of 5 stars and wrote.",
    category:"Movies",
    date:"On September 30, 2020",
    width: 450,
    height: 600,
  },
  {
    id: "20",
    title:"Pathaan (film)",
    url: "https://upload.wikimedia.org/wikipedia/en/c/c3/Pathaan_film_poster.jpg",
    content:"Pathaan is a 2023 Indian Hindi-language action thriller film directed by Siddharth Anand and produced by Aditya Chopra of Yash Raj Films.[5] The film stars Shah Rukh Khan, Deepika Padukone, and John Abraham, alongside Dimple Kapadia and Ashutosh Rana.  ",
    category:"Movies",
    date:"On 25 December 2019.",
    width: 1193,
    height: 1006,
  },
];