export const data = [
    {
      id: "A1",
      title:'Highest Grossing Hollywood Movies of All Time',
      url: "https://i0.wp.com/www.wonderslist.com/wp-content/uploads/2018/12/Highest-Grossing-Hollywood-Movies.jpg",
      content:"Every year a lot of Hollywood movies gets released. Some of them makes big profit and some fails miserably. There is a lot of craziness for Hollywood movies in the entire world. People love going to the movies and nothing is stopping them.",
      category:"Hollywood",
      date:"on october 15,2016",
      width: 500,
      height: 351,
    },
    {
      id: "B1",
      title:"Hollywood Movies series",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkOpaFZdYJsYq0KiltceBzfhOxMNsKUe8tgQ&usqp=CAU",
      content:"The witcher is being hailed by many as one of the best live-action adaption of the video games.",
      category:"Hollywood",      
      date:"on September 20, 2015.",
      width: 500,
      height: 307,
    },
    {
      id: "C1",
      title:"Vogue Hollywood Movies",
      url: "https://assets.vogue.in/photos/5de8c84a6ffadb00085fb0d2/2:3/w_2560%2Cc_limit/Gal-Gagot-as-Wonder-Woman.jpg",
      content:"From Christopher Nolan blockbusters to long-awaited sequels and a sugary-sweet Jane Austen adaptation, Vogue shortlists 2020’s most anticipated releases",
      category:"Hollywood",
      date:"On December 5, 2019.",
      width: 1280,
      height: 956,
    },
    {
      id: "D1",
      title:"The Invisible Man",
      url: "https://assets.vogue.in/photos/5de8c54faef206000819380a/master/w_1600,c_limit/003-The-Invisible-Man-Film-Guide-for-2020-Vogue-Int-2nd-December-2019-Universal-Pictures.jpg",
      content:"Elisabeth Moss gives a powerful performance in Leigh Whannell’s sci-fi horror. It follows a woman who has escaped a controlling relationship, only to find that she is being hunted by a force that nobody can see.",
      category:"Hollywood",
      date:"On December 5,2020",
      width: 500,
      height: 500,
    },
    {
      id: "E1",
      title:"Mulan , Hollywood Studios",
      url: "https://assets.vogue.in/photos/5de8c5536ffadb00085fb0ce/master/w_1600,c_limit/004-Mulan-Film-Guide-for-2020-Vogue-Int-2nd-December-2019-Alamy.jpg",
      content:"The live-action retelling of Disney’s 1998 animated film casts Chinese-American actress Liu Yifei in the lead. With rousing battle sequences, acrobatic stunts .",
      category:"Hollywood",
      date:"On 27 March 2020.",
      width: 1193,
      height: 1006,
    },
  ];
