export const data = [
    {
      id: "101",
      title:"The Gentlemen,Shaun the Sheep Movie",
      url: "https://st1.bollywoodlife.com/wp-content/uploads/2020/01/FotoJet-2020-01-20T231217.178.jpg?impolicy=Medium_Widthonly&w=360",
      content:"Wondering which Hollywood films to watch this weekend? Well, we can make your life easier as we tell you the options that you have.",
      category:"Movies",
      date:"On January 21, 2020.",
      width: 640,
      height: 427,
      related:['Recent','Images','videos','news','Blogs'],
    },
    {
      id: "102",
      title:"Warner Bros. 2021 Film Slate - New Hybrid Distribution Model",
      url: "https://assets.www.warnerbros.com/drupal-root/public/banner/media/browser/wb_film_2021_slate_hbo_max_800.png",
      content:"Warner Bros announced that it has committed to releasing its 2021 film slate via a unique, consumer-focused distribution model in which Warner Bros.",
      category:"Wine",
      date:"On December 03,2020",
      width: 500,
      height: 500,
    },
    {
        id: "103",
        title:"Holi 2022: To play or not to play, opinions vary in Salt Lake & New Town",
        content:"That is the dilemma people are facing on the day of the festival after two years of abstention but some are set to make the most of the occasion...",
        category:"Celebration",
        date:"On January 31, 2010",
        url: "https://assets.telegraphindia.com/telegraph/2022/Mar/1647554824_new-project-1.jpg",
        width: 640,
        height: 428,
      },
    {
      id: "104",
      title:'Konark Festival And International Sand Art Festival 2021 Kicks Off In Style',
      url: "https://mycitylinks.in/wp-content/uploads/2021/12/Cover-3.jpg",
      content:"Konark Festival 2021, the five-day Indian classical dance extravaganza was inaugurated by Chief Minister Naveen Patnaik at Konark on Wednesday.",
      category:"Celebration",
      date:"On october 15,2016",
      width: 500,
      height: 351,
    },
    
    {
      id: "105",
      title:"Actors Akshay Kuma and Amy Jackson Bollywood Celebrity India",
      url: "https://thumbs.dreamstime.com/b/actors-akshay-kuma-amy-jackson-bollywood-celebrity-india-actors-akshay-kumar-amy-jackson-ht-gifa-grand-opening-240342825.jpg",
      content:"Actors Akshay Kumar and Amy Jackson at the HT GIFA grand opening ceremony event in Tau Devi Lal stadium, in Gurgaon.",
      category:"Celebration",      
      date:"On September 20, 2015.",
      width: 500,
      height: 307,
    },
    {
        id: "106",
        title:"Mountains and pink flowers",
        url: "https://cdn.pixabay.com/photo/2015/04/23/22/01/mountains-736886__340.jpg",
        content:"Free landscapes images to use in your next project. Browse amazing images uploaded by the Pixabay community.",
        category:"Mountains",
        date:"On 25 December 2012.",
        width: 1193,
        height: 1006,
      },
      {
        id: "107",
        title:'Boeing 737 Max Resumes Flying U.S. Passengers After 2-Year Halt.',
        url: "https://static01.nyt.com/images/2020/12/29/us/29boeing-sub/merlin_181767753_59d7cadc-adac-4644-81c2-0e0969d78597-jumbo.jpg?quality=75&auto=webp",
        content:"American Airlines used the plane, which was grounded in March 2019 after two fatal crashes, on a flight from Miami to New York.",
        category:"Airlines",
        date:"On october 15,2016",
        width: 500,
        height: 351,
      },
  ];
