export const data = [
    {
      id: "10",
      title:"Latest from the world of film",
      url: "https://media.timeout.com/images/102136087/image.jpg",
      content:"With films dating from 1951 to 2014, this list will give you a glimpse into just how much Bollywood has changed over the last 60 years, while providing you with some absolute bangers you'll want to add to your playlists, too. ",
      category:"Musical moments",
      date:"On March 2, 2023",
      width: 640,
      height: 427,
      related:['Recent','Images','videos','news','Blogs'],
    },
    {
      id: "11",
      title:"Actors Akshay Kumar and Amy Jackson Bollywood .",
      url: "https://i.ytimg.com/vi/w89rXmSYG0w/maxresdefault.jpg",
      content:"Presenting the 31st Night Special Party Songs on Bollywood Dance Beats Remix - JUKEBOXFor Dance Songs : http://bit.ly/2bE18TVFor Evergreen Jhankar Beats Song...",
      category:"Party Songs",
      date:" On December 20, 2018",
      width: 700,
      height: 524,
    },
    {
      id: "12",
      title:"Race 3 , Latest Bollywood Film Trailer ",
      url: "https://resize.indiatvnews.com/en/resize/newbucket/730_-/2018/06/upcoming-bollywood-movie-1528459686.jpg",
      content:"Race 3 is directed by Remo D’Souza and stars Salman Khan, Anil Kapoor, Bobby Deol, Saqib Saleem, Daisy Shah and Jacqueline Fernandez in lead roles. It is produced by Tips Industries and Salman Khan films.",
      category:"Bollywood",
      date:"On June 15 2018",
      width: 2696,
      height: 3546,
    },
    {
      id: "14",
      title:'NJ - Prabhu Deva and Indian Dancers perform for Donald Trump at Edison New Jersey Hindu Indian-American',
      url: "https://thumbs.dreamstime.com/b/october-edison-nj-prabhu-deva-indian-dancers-perform-donald-trump-edison-new-jersey-hindu-indian-american-rally-84988823.jpg",
      content:"NJ - Prabhu Deva and Indian Dancers perform for Donald Trump at Edison New Jersey Hindu Indian-American rally for Humanity United Against Terror",
      category:"Bollywood",
      date:"On october 15,2016",
      width: 500,
      height: 351,
    },
    {
      id: "15",
      title:"Actors Akshay Kuma and Amy Jackson Bollywood Celebrity India",
      url: "https://thumbs.dreamstime.com/b/actors-akshay-kuma-amy-jackson-bollywood-celebrity-india-actors-akshay-kumar-amy-jackson-ht-gifa-grand-opening-240342825.jpg",
      content:"Actors Akshay Kumar and Amy Jackson at the HT GIFA grand opening ceremony event in Tau Devi Lal stadium, in Gurgaon.",
      category:"Celebration",      
      date:"On September 20, 2015.",
      width: 500,
      height: 307,
    },
    {
      id: "16",
      title:"Best Bollywood Dumb Charades Movies Really Really Hard To Guess",
      url: "https://www.scrolldroll.com/wp-content/uploads/2018/05/Movie-name-1.jpg",
      content:"Whoever came up with this name is a genius. And before you dismiss this one, do note that besides being a great Dumb Charade movie name,  this was the first Indian film for which all songs were recorded in stereophonic sound.",
      category:"Bollywood",
      date:"On April 21, 2018.",
      width: 1280,
      height: 956,
    },
    {
      id: "17",
      title:"EVERY TIME SONGS MAKE YOU TRAVEL BACK IN TIME",
      url: "https://icdn.isrgrajan.com/in/2020/09/13-recreated-Bollywood-songs-of-2020-1-696x399.jpg",
      content:"Songs and Music are the part of the life which one cannot separate their self from. People throughout history have used songs in order to relieve their past memories and allow them to express their emotions. ",
      category:"Bollywood songs",
      date:"On December 21,2021",
      width: 500,
      height: 500,
    },
    {
      id: "18",
      title:"Indian Music and Dance Show",
      content:"The Indian Bollywood Film Star Song and Dance Troupe perform on stage during Indian Music and Dance Show at Beijing Exhibition Theater on January 31, 2010 in Beijing, China. The Indian Bollywood Film Star Song and Dance Troupe stage Indian pop songs and dance scenes from classic Bollywood films, including Rhythm of Love, Jaane Kisne, and Overjoyed Rhythm.",
      category:"Dance",
      date:"On January 31, 2010",
      url: "https://i.ytimg.com/vi/UZTNacSnivw/maxresdefault.jpg",
      width: 640,
      height: 428,
    },
    {
      id: "19",
      title:"Besharam Rang, protests",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Shah_Rukh_Khan%2C_Deepika_Padukone%2C_John_Abraham_attend_the_press_conference_and_success_celebration_of_Pathaan.jpg/200px-Shah_Rukh_Khan%2C_Deepika_Padukone%2C_John_Abraham_attend_the_press_conference_and_success_celebration_of_Pathaan.jpg",
      content:"Taran Adarsh of Bollywood Hungama rated the film 4.5 out of 5 stars and termed the film a complete entertainer replete with action, emotions, patriotism, humour, thrill, and of course, the star power of Shah Rukh Khan.[73] Sukanya Verma of Rediff gave the film a rating of 4 out of 5 stars and wrote.",
      category:"Movies",
      date:"On September 30, 2020",
      width: 450,
      height: 600,
    },
    {
      id: "20",
      title:"Pathaan (film)",
      url: "https://upload.wikimedia.org/wikipedia/en/c/c3/Pathaan_film_poster.jpg",
      content:"Pathaan is a 2023 Indian Hindi-language action thriller film directed by Siddharth Anand and produced by Aditya Chopra of Yash Raj Films.[5] The film stars Shah Rukh Khan, Deepika Padukone, and John Abraham, alongside Dimple Kapadia and Ashutosh Rana.  ",
      category:"Movies",
      date:"On 25 December 2019.",
      width: 1193,
      height: 1006,
    },
  ];