export const data = [
    {
      id: "11",
      title:"Article on Health and Fitness",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-lETSmNfjkhXKuXzdwORhVfpC7j_WTAmWuQ&usqp=CAU",
      content:"Health can, generally, be measured on major three parameters: Physical, Psychological and Nutritional. Physical health means the physical appearance of a person.",
      category:"Fitness",
      date:"On March 2, 2019.",
      width: 640,
      height: 427,
    },
    {
      id: "12",
      title:"About Yoga Content",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE5X7XUna9FnCLc2o8om6q2b2tBkZ-UwIuyA&usqp=CAU",
      content:"Yoga asanas are synonymous with flexibility. Anyone who approaches yoga aims to improve their flexibility.",
      category:"Yoga",
      date:" On September 20, 2015.",
      width: 700,
      height: 524,
    },
    {
      id: "13",
      title:"Invest in your health, Healthy lifestyle concept with diet and fitness, Get fit in, fitness equipment and healthy food",
      url: "https://thumbs.dreamstime.com/z/invest-your-health-healthy-lifestyle-concept-diet-fitness-get-fit-fitness-equipment-healthy-food-invest-your-158227197.jpg",
      content:"Invest in your health , Healthy lifestyle concept with diet and fitness , Get fit in , fitness equipment and healthy food ",
      category:"healthy Food",
      date:"On September 20, 2015.",
      width: 2696,
      height: 3546,
    },
    {
      id: "14",
      title:'Working out at home with online fitness course, workout video or personal trainer service in phone. Health or sport mobile app.',
      url: "https://thumbs.dreamstime.com/z/working-out-home-online-fitness-course-workout-video-personal-trainer-service-phone-health-sport-mobile-app-144081381.jpg",
      content:"Working out at home with online fitness course, workout video or personal trainer service in phone. Health or sport mobile app in cellphone. Fit woman with smartphone and gym equipment",
      category:"Gym",
      date:"On october 15,2016",
      width: 500,
      height: 351,
    },
    {
      id: "15",
      title:"Sports nutrition and fitness equipment.",
      url: "https://media.istockphoto.com/id/1133462293/photo/sports-nutrition-and-fitness-equipment.jpg?s=1024x1024&w=is&k=20&c=fMWVeQ9izZ4sYzS6BURRU3YZ8-RVHGKZgFER55YookI=",
      content:"Sports nutrition supplements, healthy food and dumbbells on a black background. Fitness, bodybuilding, sport and healthy lifestyle concept.",
      category:"Celebration",      
      date:"On September 20, 2015.",
      width: 500,
      height: 307,
    },
    {
      id: "16",
      title:"FITNESS",
      url: "https://thumbs.dreamstime.com/z/fitness-word-cloud-sport-health-concept-58066979.jpg",
      content:"FITNESS word cloud, sport, health concept",
      category:"Fitness",
      date:"On March 2, 2019.",
      width: 1280,
      height: 956,
    },
    {
      id: "17",
      title:"Indian fitness woman runner stretching legs before run outdoor workout in the park.",
      url: "https://previews.123rf.com/images/ximagination/ximagination1512/ximagination151200258/49421575-beautiful-indian-young-woman-wearing-sportswear-and-running-on-the-track-in-the-morning.jpg",
      content:"Asian fitness woman runner stretching legs before run outdoor workout in the park. Healthy Concept.",
      category:"warmUp",
      date:"On December 21,2021",
      width: 500,
      height: 500,
    },
    {
      id: "18",
      title:"Close up . Woman do yoga outdoor",
      url: "https://thumbs.dreamstime.com/z/close-up--woman-do-yoga-outdoor-woman-exercising-vital-meditation-fitness-lifestyle-beach-sunset-background-104776221.jpg",
      content:"Close up . Woman do yoga outdoor. Woman exercising vital and meditation for fitness lifestyle in the beach sunset background. Healthy Concept",
      category:"Yoga",
      date:"On September 20, 2015.",
      width: 700,
      height: 524,
    },
    {
      id: "19",
      title:"Exercise involves engaging in physical activity",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNn7bnhac7Wz23rktk84vrypxo5SA2uiweLQ&usqp=CAU",
      content:"Whether people engage in light exercise, such as going for a walk, or high intensity activities, for example, uphill cycling or weight training, regular exercise provides a huge range of benefits for the body and mind.",
      category:"Fitness",      
      date:"On September 20, 2015.",
      width: 500,
      height: 307,
    },
    {
      id: "20",
      title:"The Fitness Factory, a one-stop-shop for all fitness needs launched",
      url: "https://bsmedia.business-standard.com/_media/bs/img/article/2022-04/14/full/20220414153207.jpg",
      content:"A Surat-based fitness enthusiast turned entrepreneur has launched The Fitness Factory, a one-stop-shop for fitness freaks and the first of its kind in India.",
      category:"Fitness",
      date:"On March 2, 2019.",
      width: 1280,
      height: 956,
    },
    {
      id: "21",
      title:"A Fresh Perspective on Physical Activity",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR54ne1jIFdEQy9yravxvo_Dp3aQm5NfUIVLQ&usqp=CAU",
      content:"In the big picture of physical activity, everything counts!  Running a 5k, sweating during spin or Krank class, and lifting weights are not the only examples of physical activity.",
      category:"Physical Activity Pyramid",
      date:"On December 21,2021",
      width: 500,
      height: 500,
    },
  ];
  