export const data = [
    {
      id: "11",
      title:"Dinner is served with family",
      url: "https://cdn3.mycity4kids.com/images/article-images/web/headersV2/img-20180821-5b7bec53d3d58.jpg",
      content:"For working households with school and college going children , breakfast is a hurried affair,to be eaten while on the go,lunch is usually packed.",
      category:"Food ",
      date:"On March 2, 2019.",
      width: 640,
      height: 427,
    },
    {
      id: "12",
      title:"How to Avoid Overindulging at Parties and Family Gatherings",
      url: "https://cdn.shopify.com/s/files/1/0114/8422/articles/How_to_Avoid_Overindulging_at_Parties_and_Family_Gatherings.png?v=1521777611",
      content:"The group mindset at holiday parties and family gatherings is to overindulge in food, drinks, and frivolity. Even after you’ve had a few extra cookies and a second margarita, it’s guaranteed someone will prod you to have a few more.",
      category:"Food",
      date:" On September 20, 2015.",
      width: 700,
      height: 524,
    },
    {
      id: "13",
      title:"Most Important Meal of the Day?",
      url: "https://www.news-medical.net/images/Article_Images/ImageForArticle_22830_16576322476612184.jpg",
      content:"Breakfast is often referred to as the most important meal of the day. In recent years it has been implicated in the control of weight, considered a cardiometabolic risk factor, and implicated in cognitive performance.",
      category:"Food",
      date:"On September 20, 2015.",
      width: 2696,
      height: 3546,
    },
    {
      id: "14",
      title:'Mother feeding her baby with spoon. Mother giving healthy food to her adorable child at home',
      url: "https://thumbs.dreamstime.com/z/mother-feeding-her-baby-son-spoon-giving-healthy-food-to-adorable-child-home-105179937.jpg",
      content:"Mother feeding her baby son with spoon. Mother giving healthy food to her adorable child at home",
      category:"Fun Moments",
      date:"On october 15,2016",
      width: 500,
      height: 351,
    },
    {
      id: "15",
      title:"Fitness Food, Nutrition. Healthy Eating Woman Drinking Smoothie",
      url: "https://thumbs.dreamstime.com/z/fitness-food-nutrition-healthy-eating-woman-drinking-smoothie-diet-fresh-detox-juice-breakfast-closeup-beautiful-smiling-74592279.jpg",
      content:"Fitness Food. Healthy Eating Woman On Diet Drinking Fresh Detox Juice, Smoothie For Breakfast. Closeup Of Beautiful Smiling Girl With Fruits And Weight Loss Drinks At Kitchen Table. Nutrition Concept",
      category:"Fitness Food",      
      date:"On September 20, 2015.",
      width: 500,
      height: 307,
    },
    {
      id: "16",
      title:"Foods to Eat in the Morning",
      url: "https://post.healthline.com/wp-content/uploads/2021/10/fruit-salad-best-breakfast-foods-1296x728-body.jpg",
      content:"A balanced breakfast typically includes protein, fiber, and produce. If you’re looking to build a healthy morning meal, try easy options like eggs, whole wheat toast with toppings, nuts, and green tea.",
      category:"costumes",
      date:"On March 2, 2019.",
      width: 1280,
      height: 956,
    },
    {
      id: "17",
      title:"Beer Soup? No. Greens? Yes.",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnX14K7ANHrOoIgHNdIjOu4chJ-DjaOfOwyw&usqp=CAU",
      content:"American breakfasts are heavy on foods that make us heavy.Credit...Alanna Taylor-Tobin and Sarah Menanix for The New York Times.",
      category:"Wine",
      date:"On December 21,2021",
      width: 500,
      height: 500,
    },
    {
      id: "18",
      title:"Healthy People Eat In Breakfast",
      content:"A right breakfast not only keeps you fit but also curbs your mid-meal cravings. Choosing a healthy breakfast option is a complex task, especially, when you desire to taste as well as nutrition at the same time.",
      category:"Food",
      date:"On January 31, 2010",
      url: "https://post.healthline.com/wp-content/uploads/2020/08/salad-for-breakfast-732x549-thumbnail-732x549.jpg",
      width: 640,
      height: 428,
    },
    {
      id: "19",
      title:"Food waste",
      url: "https://foodprint.org/wp-content/uploads/2018/10/food-waste-problem.jpg",
      content:"A pile of food waste, such as eggshells and fruit and vegetable peels, on a white background",
      category:"Food",
      date:"On September 30, 2020",
      width: 450,
      height: 600,
    },
    {
      id: "20",
      title:"Reduce food waste and save some money",
      url: "https://softengine.com/wp-content/uploads/2021/04/zero-waste-300x200.jpeg",
      content:"As per the Food Waste Index Report 2021 by the United Nations Environment Programme (UNEP), Indians throw away 50 kg of food per person every year.",
      category:"Wasting Food",
      date:"On 25 December 2012.",
      width: 1193,
      height: 1006,
    },
  ];