export const data = [
    {
      id: "A1",
      title:"A Quiet Place",
      url: "https://www.indiewire.com/wp-content/uploads/2018/10/a_quiet_place_still_1.jpg",
      content:"Hollywood Oscar campaigners earn their big bucks for figuring out the best possible way to not only gain an Oscar nomination, but actually take home a gold statue. ",
      category:"Hollywood",
      date:"On October 23, 2018",
      width: 640,
      height: 427,
    },
    {
      id: "A2",
      title:"John Krasinski Pushed to Cast a Deaf Actress for ‘A Quiet Place’",
      url: "https://www.hollywoodreporter.com/wp-content/uploads/2018/04/a_quiet_place_still_6.jpg?w=1296",
      content:"Screenwriters Bryan Woods and Scott Beck recall how the actor-director fought to make Millicent Simmonds his onscreen daughter, a move that 'brought an extra depth to the film.'",
      category:"Hollywood",
      date:" On September 20, 2018",
      width: 700,
      height: 524,
    },
    {
      id: "A3",
      title:"Hollywood Synopsis",
      url: "https://static.toiimg.com/thumb/msid-66052420,width-219,height-317,imgsize-14938/66052420.jpg",
      content:"Watch out for the thrilling moments, gravity-defying stunts and special effects that compensate for what’s missing in making it the action-adventure extravaganza it was expected to be.Read More",
      category:"Hollywood",
      date:"On September 20, 2019.",
      width: 2696,
      height: 3546,
    },
    {
      id: "A4",
      title:'Hollywood actress style',
      url: "https://pickytop.com/wp-content/uploads/2020/03/Gal-Gadot.jpg",
      content:"Vintage lady posing with authentic hollywood lighting,Mother giving healthy food to her adorable child at home",
      category:"Hollywood",
      date:"On october 15,2016",
      width: 500,
      height: 351,
    },
    {
      id: "A5",
      title:"Universal Studios Hollywood Globe in Los Angeles",
      url: "https://thumbs.dreamstime.com/z/universal-studios-hollywood-globe-los-angeles-14844803.jpg",
      content:"Universal Studios Hollywood famous globe at the beginning of the City Walk in Los Angeles California",
      category:"Hollywood",      
      date:"On September 20, 2015.",
      width: 500,
      height: 307,
    },
    {
      id: "A6",
      title:"Hollywood : Heart of the American cinema",
      url: "https://cdn.slidesharecdn.com/ss_thumbnails/hollywoodstudiosystem-140425045759-phpapp01-thumbnail.jpg?width=600&height=600&fit=bounds",
      content:"Hollywood : Heart of the American cinema . The Liberation of Skopje at Sarajevo Film Festival. Filmed at Sarajevo during the Avant Premiere Press Junket. Date: August 13th 2016, time around 19.00. Rade Serbedzija is a famous actor who acted in several Hollywood films, as well as many films made in Former Yugoslavia. He is also a film director. His son Danilo Serbedzija is a film director.",
      category:"Hollywood",
      date:"On March 2, 2019.",
      width: 1280,
      height: 956,
    },
    {
      id: "A7",
      title:"Movie Film Crew on location RIPD movie",
      url: "https://thumbs.dreamstime.com/z/movie-film-crew-location-21618695.jpg",
      content:"Peter M. Lenkov (seated) producer and writer of the upcoming Jeff Bridges and Ryan Reynolds graphic novel movie R. I. P. D. about zombie police set to be released in 2013, filming in downtown Boston on Oct. 15, 2011. Directed by Robert Schwentke. Starring: Ryan Reynolds, Jeff Bridges, Kevin Bacon, Stephanie Szostak, Mary-Louise Parker, Marisa Miller, Mike OMalley, James Hong, Robert Knepper",
      category:"Hollywood",
      date:"On December 21,2021",
      width: 500,
      height: 500,
    },
    {
      id: "A8",
      title:"Peter M. Lenkov (seated) producer and writer of the upcoming Jeff Bridges and Ryan Reynolds graphic novel movie R. I. P. D. about zombie police set to be released in 2013, filming in downtown Boston on Oct. 15, 2011. Directed by Robert Schwentke. Starring: Ryan Reynolds, Jeff Bridges, Kevin Bacon, Stephanie Szostak, Mary-Louise Parker, Marisa Miller, Mike OMalley, James Hong, Robert Knepper",
      content:"SAINT PETERSBURG, RUSSIA - JULY 22, 2017:Film Crew On Location. 4K Camera Cinematographer. Filmmaking. Set, scenery of the roadside cafe 80's style",
      category:"Hollywood",
      date:"On January 31, 2010",
      url: "http://studenttravelplanningguide.com/wp-content/uploads/2017/06/home_images_nys_green_a.jpg",
      width: 640,
      height: 428,
    },
    {
      id: "A9",
      title:"Galaxy`s Edge, Disney World, Hollywood Studios",
      url: "https://thumbs.dreamstime.com/z/galaxy-s-edge-disney-world-hollywood-studios-wall-poster-conceptual-design-new-star-wars-section-walt-orlando-141315570.jpg",
      content:"Wall poster with a conceptual design of the new Galaxy`s Edge Star Wars section of Hollywood Studios at Walt Disney World in Orlando, FL. Florida is a popular travel destination for people and tourists who travel on vacation or holiday.",
      category:"Hollywood",
      date:"On 25 December 2012.",
      width: 1193,
      height: 1006,
    },
    {
      id: "A10",
      title:"On location film crew making a movie RIPD",
      url: "https://thumbs.dreamstime.com/z/location-film-crew-making-movie-24578214.jpg",
      content:"Stunt car scene - Filming graphic novel movie R.I.P.D. about zombie police set to be released in 2013, filming in downtown Boston on Oct. 15, 2011. Directed by Robert Schwentke. Starring: Ryan Reynolds, Jeff Bridges, Kevin Bacon, Stephanie Szostak, Mary-Louise Parker, Marisa Miller, Mike OMalley, James Hong, Robert Knepper",
      category:"Hollywood",
      date:"on September 30, 2020",
      width: 450,
      height: 600,
    },
  ];