export const data = [
    {
      id: "1",
      title:"Computer Science & Engineering",
      url: "https://vita.vision.org.in/wp-content/uploads/2020/08/Emerging-Technology-750x458.jpg",
      content:"The field of Computer Science is witnessing new innovation and research like never before. We have reached a place where exponential technologies like Artificial Intelligence, IoT, Data Science. ",
      date:"On March 2, 2022.",
      category:"Technology",
      width: 640,
      height: 427,
      related:['Recent','Images','videos','news','Blogs'],
    },
    {
      id: "2",
      title:"Pepper Robot Assistant Information touch screen Humanoid technology. ",
      url: "https://i.ytimg.com/vi/hugjyl0QbaI/maxresdefault.jpg",
      content:"Most Exciting, Emerging Technologies for Computer Science Graduates Mind Blowing TechnologiesFor Computer Science Graduates.",
      category:"Technology",
      date:" On April 16, 2018 ",
      width: 700,
      height: 524,
    },
    {
      id:"3",
      title:"Online Reviews Evaluation Concept with computer halogram scanning on data of business and all new technology",
      url: "https://img.freepik.com/free-photo/ai-nuclear-energy-background-future-innovation-disruptive-technology_53876-129783.jpg?size=626&ext=jpg",
      content:"Business woman drawing global structure networking and data exchanges customer connection on dark background",
      category:"Technology",
      date:"On September 20, 2015.",
      width: 2696,
      height: 3546,
    },
    {
      id:"4",
      title:'Sustainable development, eco friendly lifestyle concept. 3d rend',
      url: "https://thumbs.dreamstime.com/z/sustainable-development-eco-friendly-lifestyle-concept-d-rend-sustainable-development-eco-friendly-lifestyle-concept-d-rendering-116932229.jpg",
      content:"Sustainable development, eco friendly lifestyle concept. 3d rendering of arrow circle icon on fresh spring meadow with blue sky in background.",
      category:"Technology",
      date:"On october 15,2016",
      width: 500,
      height: 351,
    },
    {
      id:"5",
      title:"Exposure of businessman using the tablet with cityscape and financial graph",
      url: "https://img.freepik.com/free-photo/double-exposure-businessman-using-tablet-with-cityscape-financial-graph-blurred-buildi_1258-84463.jpg?w=826&t=st=1675274430~exp=1675275030~hmac=b9517d3c28ef00ec98b534b3e15a4fc62e0234a95528bbfdf7eacd3b697a99e2",
      content:"Double exposure of businessman using the tablet with cityscape and financial graph on blurred buildi....",
      category:"Technology",      
      date:"On September 20, 2015.",
      width: 500,
      height: 307,
    },
    {
      id: "6",
      title:"Laboratory Test Tube in Science Research Lab",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXzV9QLuxdMlTIYd5VJjQhziS6_jQYmhamWA&usqp=CAU",
      content:"Scientist hand holding a laboratory glass test tube filled with yellow liquid for an experiment in a science research lab",
      category:"Technology",
      date:"On March 2, 2019.",
      width: 1280,
      height: 956,
    },
    {
      id: "7",
      title:"Laboratory",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNs5zUjnkrS6jRMN0gU83GnOLYkBnJKFUdxA&usqp=CAU",
      content:"Scientists working at the laboratory",
      category:"Technology",
      date:"On December 21,2021",
      width: 500,
      height: 500,
    },
    {
      id: "8",
      title:"Flat icons technology, social media, network, computer concept. Abstract background with objects group of elements. star smiley",
      content:"Flat icons technology, social media, network, computer concept. Abstract background with objects with group of elements. star smiley face sale. Share, Like, Comment, Vector illustration Twitter, YouTube, WhatsApp, Snapchat, Facebook, instagram",
      category:"Technology",
      date:"On January 31, 2010",
      url: "https://cdn.pixabay.com/photo/2014/03/22/22/15/social-media-292988_960_720.jpg",
      width: 640,
      height: 428,
    },
    {
      id: "9",
      title:"Collection of old audio cassette tapes isolated on white background vintage music and technology concept",
      url: "https://thumbs.dreamstime.com/z/collection-old-audio-cassette-tapes-isolated-white-background-vintage-music-technology-concept-189782689.jpg",
      content:"Collection of old audio cassette tapes isolated on white background, vintage music and technology concept",
      category:"Technology",
      date:"On September 30, 2020",
      width: 450,
      height: 600,
    },
    {
      id: "10",
      title:"Grabbing money",
      url: "https://thumbs.dreamstime.com/z/grabbing-money-18095541.jpg",
      content:"Grabbing money isolated on white background ",
      category:"Technology",
      date:"On 25 December 2012.",
      width: 1193,
      height: 1006,
    },
  ];